output: /tmp/results2
timeoutSeconds: 1000
common:
  numFeatures: 10
  numExamples: [1, 3]
  numPartitions: 3
  randomSeed: [1, 2, 3]
benchmarks:
  - name: classification.LogisticRegression
    common:
      numFeatures: 100
    extra:
      regParam: 0.1
      tol: [0.2, 0.1]
